services:
  server:
    image: vladmarlo/todoer_backend:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    image: vladmarlo/todoer_migrator
    restart: no
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 15
volumes:
  db-data:

